# Generated by Django 5.2.7 on 2025-12-05 13:26

from django.conf import settings
from django.db import migrations, models


def populate_published_at(apps, schema_editor):
    Post = apps.get_model("blog", "Post")
    Post.objects.filter(status="published", published_at__isnull=True).update(
        published_at=models.F("created_at")
    )


def noop(apps, schema_editor):
    """Reverse operation is a no-op."""
    # Nothing to do on reverse; keeping published_at values is fine.
    return


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["status", "published_at"],
                name="blog_post_status_5b2843_idx",
            ),
        ),
        migrations.RunPython(populate_published_at, noop),
    ]
